### ISSUE TITLE
docker build -t="reliable-master" . 报错

### ISSUE THREAD

**Issue by wangyunshuai** [xudafeng/reliable#51]
1, 使用了阿里云的镜像加速器
```
Mac: 10.12.1

➜  ~ docker --version
Docker version 1.12.3, build 6b644ec

➜  ~ docker-machine --version
docker-machine version 0.8.2, build e18a919

➜  ~ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

```
> kerberos@0.0.22 install /reliable-master/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make[1]: Entering directory `/reliable-master/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make[1]: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v4.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.39-boot2docker
gyp ERR! command "/root/.nvm/versions/node/v4.5.0/bin/node" "/root/.nvm/versions/node/v4.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /reliable-master/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by brunoyang** [comment]
请问解决了吗？

**Comment by wangyunshuai** [comment]
@brunoyang 没有

**Comment by CodeToSurvive1** [comment]
试了下 这个报错不影响

**Comment by CodeToSurvive1** [comment]
@wangyunshuai 这个试下 应该好了
