### ISSUE TITLE
reliable-master docker部署后不能访问管理后台!!!

### ISSUE THREAD

**Issue by pepsicoffee** [xudafeng/reliable#59]
部署方式:docker
**OS:**CentOS7.4
**- uname -r**
3.10.0-862.14.4.el7.x86_64

**- docker --version**
Docker version 1.13.1, build 8633870/1.13.1(备注:卸载1.13.1版本,通过更新docker-ce-18.06.1.ce-3.el7 版本试了也不行)
**- docker-compose --version**
docker-compose version 1.23.1, build b02f130
**-进入docker-compose目录后:make start结果如下:**
Stopping reliable-master ... done
Stopping reliable_mongo  ... done
Stopping reliable_redis  ... done
Removing reliable-master ... done
Removing reliable_mongo  ... done
Removing reliable_redis  ... done
RELIABLE_MASTER_PORT=8080 docker-compose build
redis uses an image, skipping
mongo uses an image, skipping
reliable-master uses an image, skipping
RELIABLE_MASTER_PORT=8080 docker-compose up -d --remove-orphans
Creating reliable_redis ... done
Creating reliable_mongo ... done
Creating reliable-master ... done
**-docker ps:**
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
ca94390cb108        reliable-master     "/entrypoint.sh /r..."   2 minutes ago       Up 2 minutes        0.0.0.0:8080->8080/tcp   reliable-master
4bd62399aa1a        mongo               "docker-entrypoint..."   2 minutes ago       Up 2 minutes        27017/tcp                reliable_mongo
09741187ab83        redis               "docker-entrypoint..."   2 minutes ago       Up 2 minutes        6379/tcp                 reliable_redis

**docker logs ca94390cb108(master的containerID)**
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:44:14 [master] pid:18 worker fork success
>> index.js:62:14 [master] pid:18 worker online
>> index.js:62:14 [master] pid:18 worker online
>> index.js:62:14 [master] pid:18 worker online
>> index.js:62:14 [master] pid:18 worker online
>> index.js:62:14 [master] pid:18 worker online
>> index.js:62:14 [master] pid:18 worker online
>> index.js:62:14 [master] pid:18 worker online
>> index.js:62:14 [master] pid:18 worker online
/reliable-master/node_modules/koa-redis/node_modules/debug/src/node.js:132
	let val = process.env[key];
	^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/reliable-master/node_modules/koa-redis/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/reliable-master/node_modules/koa-redis/index.js:17:13)
    at Module._compile (module.js:409:26)
/reliable-master/node_modules/koa-redis/node_modules/debug/src/node.js:132
	let val = process.env[key];
	^^^
**sudo lsof -i:8080**
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 6131 root    4u  IPv6 171062      0t0  TCP *:webcache (LISTEN)
**ps aux|grep docker**
root      5002  0.1  0.2 1111700 41308 ?       Ssl  16:22   0:01 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --init-path=/usr/libexec/docker/docker-init-current --seccomp-profile=/etc/docker/seccomp.json --selinux-enabled --log-driver=journald --signature-verification=false --storage-driver overlay2
root      5012  0.0  0.0 745020 10112 ?        Ssl  16:22   0:00 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtimedocker-runc --runtime-args --systemd-cgroup=true
root      5998  0.0  0.0 347908  5668 ?        Sl   16:30   0:00 /usr/bin/docker-containerd-shim-current 4bd62399aa1a5e4f5ab9c9dddbed536b48279420258f5273df8baaaa15e5a74f /var/run/docker/libcontainerd/4bd62399aa1a5e4f5ab9c9dddbed536b48279420258f5273df8baaaa15e5a74f /usr/libexec/docker/docker-runc-current
root      5999  0.0  0.0 275328  3640 ?        Sl   16:30   0:00 /usr/bin/docker-containerd-shim-current 09741187ab8367407e3b27715cc00a0aad1c48bcd350e23f2f552ced20c0000b /var/run/docker/libcontainerd/09741187ab8367407e3b27715cc00a0aad1c48bcd350e23f2f552ced20c0000b /usr/libexec/docker/docker-runc-current
root      6131  0.0  0.0 116564  1832 ?        Sl   16:30   0:00 /usr/libexec/docker/docker-proxy-current -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.17.0.4 -container-port 8080
root      6137  0.0  0.0 413188  4128 ?        Sl   16:30   0:00 /usr/bin/docker-containerd-shim-current ca94390cb108340b7e214a9a3289dc608aa26bff53e7ac1801e451d036c27925 /var/run/docker/libcontainerd/ca94390cb108340b7e214a9a3289dc608aa26bff53e7ac1801e451d036c27925 /usr/libexec/docker/docker-runc-current

**firewall-cmd --state**
not running

结果:应该已经将本机端口映射到容器端口8080,但访问远程访问192.168.*.*:8080提示连接失败(192.168.*.*为该服务器网址),

**Comment by pepsicoffee** [comment]
nobody?

**Comment by pepsicoffee** [comment]
nobody here?

**Comment by pepsicoffee** [comment]
nobody here?
